import React from 'react'
import { getBadges } from '../lib/persistence'
export default function Home({ user }){
  const key=k=> user?`${user.email}_${k}`:k
  const streakCurrent=Number(localStorage.getItem(key('streak_current'))||0)
  const streakBest=Number(localStorage.getItem(key('streak_best'))||0)
  const badges=getBadges(user)
  const translateProgress=Number(localStorage.getItem(key('translate_progress'))||0)
  const translateStage=Number(localStorage.getItem(key('translate_stage'))||1)
  const rounds=Number(localStorage.getItem(key('wordorder_rounds'))||0)
  const correct=Number(localStorage.getItem(key('wordorder_correct'))||0)
  const woAcc=rounds ? Math.round((correct/rounds)*100) : 0
  const avgScore=Number(localStorage.getItem(key('translate_avgScore'))||0)
  return (<div className="relative"><div className="pointer-events-none absolute inset-0 opacity-30"><div className="absolute -left-10 top-16 w-[140%] h-64 rotate-[-6deg] bg-[radial-gradient(circle,rgba(16,185,129,0.35)_2px,transparent_3px)] bg-[length:24px_24px]"></div><div className="absolute -right-10 bottom-16 w-[140%] h-64 rotate-[8deg] bg-[radial-gradient(circle,rgba(59,130,246,0.35)_2px,transparent_3px)] bg-[length:24px_24px]"></div></div><div className="relative z-10 space-y-6"><div className="p-6 rounded-3xl bg-white/80 dark:bg-zinc-900/80 shadow"><div className="flex items-center justify-between"><div><div className="text-lg font-semibold">Your Roadmap</div><div className="text-xs text-zinc-500">Daily streak <b>{streakCurrent}</b> • Best <b>{streakBest}</b></div></div><div className="flex gap-1">{[...Array(Math.min(streakCurrent,7))].map((_,i)=>(<span key={i} className="w-2 h-2 rounded-full bg-emerald-500 inline-block"></span>))}</div></div><div className="grid md:grid-cols-3 gap-4 mt-4"><RoadCard title="Translate" subtitle={`Stage ${translateStage}`} value={translateProgress} /><RoadCard title="Word Order" subtitle={`Accuracy ${woAcc}%`} value={woAcc} /><RoadCard title="Mastery" subtitle={`Avg score ${avgScore||0}`} value={Math.min(100, Math.round(avgScore||0))} /></div></div><div className="p-6 rounded-3xl bg-white/80 dark:bg-zinc-900/80 shadow"><div className="flex items-center justify-between mb-3"><div className="text-lg font-semibold">Badges</div><div className="text-xs text-zinc-500">Total {badges.length}</div></div><div className="flex flex-wrap gap-2">{badges.length===0 ? (<div className="text-sm text-zinc-500">No badges yet — jump into a study mode to earn some!</div>) : badges.map(b=>(<div key={b.id} className="px-3 py-1.5 rounded-full border border-emerald-300 bg-emerald-50 text-emerald-700 text-xs">{b.title}</div>))}</div></div></div></div>)}
function RoadCard({title,subtitle,value}){return(<div className="rounded-2xl border border-zinc-200 dark:border-zinc-700 p-4 bg-gradient-to-br from-white to-emerald-50 dark:from-zinc-900 dark:to-zinc-800"><div className="flex items-center justify-between mb-2"><div className="font-medium">{title}</div><div className="text-xs text-zinc-500">{subtitle}</div></div><div className="h-3 rounded-full bg-zinc-200 overflow-hidden"><div className="h-full bg-gradient-to-r from-emerald-400 to-amber-400" style={{width:`${Math.max(0,Math.min(100,value))}%`}}></div></div></div>)}
